name: Test application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: 3.8.5-slim

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Run tests
        run: pytest
